# Generated by Django 4.0.5 on 2022-06-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
