# Generated by Django 4.0.5 on 2022-06-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount_api', '0002_alter_useraccount_email_alter_useraccount_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.TextField(),
        ),
    ]
