# Generated by Django 4.0.5 on 2022-06-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount_api', '0003_alter_useraccount_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username',
        ),
    ]
